telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/yucca/project/LearnPython/BotLearn/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/yucca/project/LearnPython/BotLearn/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 32, in planet_user
    user_planet = update.message.text.split( )[1].lower()
IndexError: list index out of range
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/yucca/project/LearnPython/BotLearn/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/yucca/project/LearnPython/BotLearn/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 32, in planet_user
    user_planet = update.message.text.split( )[1].lower()
IndexError: list index out of range
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/yucca/project/LearnPython/BotLearn/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/yucca/project/LearnPython/BotLearn/env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 32, in planet_user
    user_planet = update.message.text.split( )[1].lower()
IndexError: list index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
